# Image scaling and resizing

In [8]:
import cv2
import matplotlib.pyplot as plt

img = cv2.imread("pic.jpg")

img_scaled = cv2.resize(img, None, fx=0.5, fy=0.5, interpolation= cv2.INTER_LINEAR)

img_scaledd = cv2.resize(img, None, fx=0.5, fy=0.5, interpolation= cv2.INTER_AREA)

img_scale = cv2.resize(img, None, fx=5.0, fy=5.0, interpolation= cv2.INTER_AREA)
cv2.imwrite("p.jpg", img_scale)


print(img.shape)
print(img_scaled.shape)
print(img_scaledd.shape)
print(img_scale.shape)##high resolution

(417, 626, 3)
(208, 313, 3)
(208, 313, 3)
(2085, 3130, 3)


# Affine Transformation

In [ ]:
->positional transformation of image

In [10]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

img = cv2.imread("pic.jpg")
num_rows, num_cols = img.shape[:2]

src_pt=np.float32([[0,0], [num_cols-1,0], [num_cols, num_rows-1], [num_cols, num_rows-1]])
des_pt =np.float32([[0,0], [num_cols-1,0], [int(0.3*num_cols), num_rows-1], [int(0.6*num_cols), num_rows-1]])

project_matrix = cv2.getPerspectiveTransform(src_pt,des_pt)

project_matrix


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [20]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

img = cv2.imread("pic.jpg")
num_rows, num_cols = img.shape[:2]

src_pt=np.float32([[0,0], [num_cols-1,0], [0, num_rows-1], [num_cols, num_rows-1]])
des_pt =np.float32([[int(0.3*num_cols),0], [int(0.6*(num_cols-1)),0], [0, num_rows-1], [num_cols, num_rows-1]])

project_matrix = cv2.getPerspectiveTransform(src_pt,des_pt)

print(project_matrix)

img_out =cv2.warpPerspective(img, project_matrix, (num_cols,num_rows))
cv2.imwrite("res.jpg",img_out)


[[ 3.00800000e-01 -4.49519231e-01  1.87000000e+02]
 [ 9.08041835e-17  3.00800000e-01  0.00000000e+00]
 [ 2.18628534e-19 -1.68076923e-03  1.00000000e+00]]


True

In [42]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

img = cv2.imread("pic.jpg")
num_rows, num_cols = img.shape[:2]

src_pt=np.float32([[0,0], [num_cols-1,0], [0, num_rows-1], [num_cols, num_rows-1]])
des_pt =np.float32([[0,0], [num_cols-1,int(0.25*num_rows)], [0, num_rows-1], [num_cols, int(0.77*(num_rows-1))]])

project_matrix = cv2.getPerspectiveTransform(src_pt,des_pt)
print(src_pt)
print("\n")
print(des_pt)
print("\n")
print(project_matrix)

img_out =cv2.warpPerspective(img, project_matrix, (num_cols,num_rows))
cv2.imwrite("new.jpg",img_out)


[[  0.   0.]
 [625.   0.]
 [  0. 416.]
 [626. 416.]]


[[  0.   0.]
 [625. 104.]
 [  0. 416.]
 [626. 320.]]


[[ 1.92455954e+00  2.66880535e-19 -1.11022302e-16]
 [ 3.20246707e-01  9.98520705e-01 -8.07687250e-15]
 [ 1.47929526e-03 -3.55599822e-06  1.00000000e+00]]


True

In [ ]:
##Image concept?

# Image Wraping

In [48]:
import math
import matplotlib.pyplot as plt
import numpy as np

img = cv2.imread("pic.jpg", cv2.IMREAD_GRAYSCALE)

rows, cols = img.shape

img_output = np.zeros(img.shape)

for i in range(rows):
    for j in range(cols):
        
        offset_x = int(80.0*math.sin(2*3.14*i/180))
        offset_y = 0
        
        if j+offset_x < cols:
            img_output[i,j] = img[i,(j+offset_x)]
        
        else:
            img_output[i,j]=0
            
cv2.imwrite("final.jpg", img_output)


True

In [49]:
import math
import matplotlib.pyplot as plt
import numpy as np

img = cv2.imread("pic.jpg", cv2.IMREAD_GRAYSCALE)

rows, cols = img.shape

img_output = np.zeros(img.shape)

for i in range(rows):
    for j in range(cols):
        
        offset_y = int(80.0*math.sin(2*3.14*j/180))
        offset_x = 0
        
        if i+offset_y < rows:
            img_output[i,j] = img[(i+offset_y),j]
        
        else:
            img_output[i,j]=255
            
cv2.imwrite("final1.jpg", img_output)


True