In [2]:
import numpy as np
x=np.array([12,34])
print(x)

[12 34]


In [3]:
type(x)

numpy.ndarray

In [5]:
np.zeros((5,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [10]:
np.random.randn(4)

array([ 0.59935817,  0.64409189, -0.11675715,  0.32181476])

In [19]:
np.random.randint(12,56)

35

In [20]:
np.eye(4)##generates identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.linspace(1,8,4)

array([1.        , 3.33333333, 5.66666667, 8.        ])

In [32]:
np.linspace(1,9,8)

array([1.        , 2.14285714, 3.28571429, 4.42857143, 5.57142857,
       6.71428571, 7.85714286, 9.        ])

In [33]:
np.logspace(2,3,4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [34]:
np.logspace(0,8,11)

array([1.00000000e+00, 6.30957344e+00, 3.98107171e+01, 2.51188643e+02,
       1.58489319e+03, 1.00000000e+04, 6.30957344e+04, 3.98107171e+05,
       2.51188643e+06, 1.58489319e+07, 1.00000000e+08])

In [35]:
np.linspace(2,3,4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [36]:
np.linspace(0,8,11)

array([0. , 0.8, 1.6, 2.4, 3.2, 4. , 4.8, 5.6, 6.4, 7.2, 8. ])

In [38]:
x=np.array([12,34])
x

array([12, 34])

In [39]:
x[0]=99
x

array([99, 34])

In [40]:
x.dtype=np.float32
x

array([1.39e-43, 4.76e-44], dtype=float32)

In [41]:
xx=np.array(['a','b','h'],dtype=np.object)
xx

array(['a', 'b', 'h'], dtype=object)

In [43]:
xx=np.array([('a','b','h')])
xx

array([['a', 'b', 'h']], dtype='<U1')

In [54]:
z=np.random.randn(56)
z

array([-0.25931404,  0.15267245,  0.26735521, -0.78553574,  1.03500945,
       -0.94120476, -1.10020159, -2.3993921 , -0.33322964, -0.28242134,
       -0.34705777,  1.116828  ,  0.25779508, -1.30408013,  0.76520251,
       -1.46084063, -0.99478615, -0.09154859,  1.57412054, -1.07639539,
       -1.25762363, -1.31783619, -1.494797  , -0.7628729 ,  0.26426703,
       -0.58380982,  1.0421643 ,  0.02137768, -0.03220619,  0.16389098,
       -1.12209757,  1.35461814, -0.05377256, -1.58568831,  0.31582423,
        0.42041557,  0.50629496,  1.57251988,  0.355785  ,  0.07634771,
       -0.09645391,  1.54434897, -0.11118189, -0.35584056,  0.52421498,
        1.50502732,  0.48246307, -0.69156622,  0.27857996, -0.98631991,
        1.31540316,  0.45681844, -0.12721081,  0.01067981,  1.53328054,
       -0.64451918])

In [55]:
z.reshape(7,8)

array([[-0.25931404,  0.15267245,  0.26735521, -0.78553574,  1.03500945,
        -0.94120476, -1.10020159, -2.3993921 ],
       [-0.33322964, -0.28242134, -0.34705777,  1.116828  ,  0.25779508,
        -1.30408013,  0.76520251, -1.46084063],
       [-0.99478615, -0.09154859,  1.57412054, -1.07639539, -1.25762363,
        -1.31783619, -1.494797  , -0.7628729 ],
       [ 0.26426703, -0.58380982,  1.0421643 ,  0.02137768, -0.03220619,
         0.16389098, -1.12209757,  1.35461814],
       [-0.05377256, -1.58568831,  0.31582423,  0.42041557,  0.50629496,
         1.57251988,  0.355785  ,  0.07634771],
       [-0.09645391,  1.54434897, -0.11118189, -0.35584056,  0.52421498,
         1.50502732,  0.48246307, -0.69156622],
       [ 0.27857996, -0.98631991,  1.31540316,  0.45681844, -0.12721081,
         0.01067981,  1.53328054, -0.64451918]])

In [49]:
z.reshape(25,1)##returns

array([[-0.34600946],
       [-1.19093856],
       [-0.49306164],
       [ 0.23257597],
       [-2.57542822],
       [ 0.69978331],
       [-1.38453032],
       [-0.66731833],
       [ 0.62447711],
       [-1.61279394],
       [ 0.07726199],
       [-0.34199832],
       [ 0.0059425 ],
       [ 0.04921001],
       [-1.61080738],
       [-1.45382161],
       [ 1.87831122],
       [-1.75416017],
       [ 0.17029875],
       [-0.85377097],
       [-0.81998071],
       [ 0.75213716],
       [-0.86714045],
       [-0.21248229],
       [-0.44018678]])

In [50]:
z.reshape(-1,1)

array([[-0.34600946],
       [-1.19093856],
       [-0.49306164],
       [ 0.23257597],
       [-2.57542822],
       [ 0.69978331],
       [-1.38453032],
       [-0.66731833],
       [ 0.62447711],
       [-1.61279394],
       [ 0.07726199],
       [-0.34199832],
       [ 0.0059425 ],
       [ 0.04921001],
       [-1.61080738],
       [-1.45382161],
       [ 1.87831122],
       [-1.75416017],
       [ 0.17029875],
       [-0.85377097],
       [-0.81998071],
       [ 0.75213716],
       [-0.86714045],
       [-0.21248229],
       [-0.44018678]])

In [51]:
z.reshape(1,-1)

array([[-0.34600946, -1.19093856, -0.49306164,  0.23257597, -2.57542822,
         0.69978331, -1.38453032, -0.66731833,  0.62447711, -1.61279394,
         0.07726199, -0.34199832,  0.0059425 ,  0.04921001, -1.61080738,
        -1.45382161,  1.87831122, -1.75416017,  0.17029875, -0.85377097,
        -0.81998071,  0.75213716, -0.86714045, -0.21248229, -0.44018678]])

In [59]:
##resize=modifies the object


In [57]:
z.ravel()

array([-0.25931404,  0.15267245,  0.26735521, -0.78553574,  1.03500945,
       -0.94120476, -1.10020159, -2.3993921 , -0.33322964, -0.28242134,
       -0.34705777,  1.116828  ,  0.25779508, -1.30408013,  0.76520251,
       -1.46084063, -0.99478615, -0.09154859,  1.57412054, -1.07639539,
       -1.25762363, -1.31783619, -1.494797  , -0.7628729 ,  0.26426703,
       -0.58380982,  1.0421643 ,  0.02137768, -0.03220619,  0.16389098,
       -1.12209757,  1.35461814, -0.05377256, -1.58568831,  0.31582423,
        0.42041557,  0.50629496,  1.57251988,  0.355785  ,  0.07634771,
       -0.09645391,  1.54434897, -0.11118189, -0.35584056,  0.52421498,
        1.50502732,  0.48246307, -0.69156622,  0.27857996, -0.98631991,
        1.31540316,  0.45681844, -0.12721081,  0.01067981,  1.53328054,
       -0.64451918])

In [66]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [79]:
a[0][1]=9
a[1][1]=4
a

array([[1., 9., 1.],
       [1., 4., 1.],
       [1., 1., 1.]])

In [83]:
np.log(a)

array([[0.        , 2.19722458, 0.        ],
       [0.        , 1.38629436, 0.        ],
       [0.        , 0.        , 0.        ]])

In [82]:
a.T##transpose

array([[1., 1., 1.],
       [9., 4., 1.],
       [1., 1., 1.]])

In [76]:
w=np.ones((3,3))
w

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [78]:
##multiple two matrix
np.matmul(a,w)

array([[11., 11., 11.],
       [ 6.,  6.,  6.],
       [ 3.,  3.,  3.]])