In [27]:
def list_operation(gallery):
    
    sum=0
    avg=0
    max=-999999
    min=999999
    
    length=len(gallery)
    
    for values in gallery:
        sum=sum+values
#         if min>values:
#             min=values
#         if max<values:
#             max=values
    
    avg=int(sum/length)
#     print("The average is "+ str(avg))
#     print("The minimum value is ",min)
#     print("The maximum value is ",max)
    return avg

list_operation([2,6,4,8,0,9,5,10,11])

6

In [29]:
%timeit list_operation([x for x in range(1250)])###gives avg time of execution

235 µs ± 60.3 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [31]:
import numpy as np
x=np.array([x for x in range(1250)])
%timeit np.average(x)

18.9 µs ± 134 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [33]:
import time

t1=time.time()

list_operation([x for x in range(1250)])

t2=time.time()

t2-t1

0.0

In [34]:
x=np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
y=np.array((9,2,3))
y

array([9, 2, 3])

In [49]:
x+y

array([[10.,  3.,  4.],
       [10.,  3.,  4.],
       [10.,  3.,  4.]])

In [46]:
yy=y.reshape((-1,1))
yy

array([[1],
       [2],
       [3]])

In [47]:
x+y

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [50]:
how numpy cv is used??

Object `used` not found.


In [ ]:
how numpy cv is used

In [ ]:
numpy??
